/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(messaging_BasePacket, messaging_BasePacket, AUTO)


PB_BIND(messaging_TelemetryPacket, messaging_TelemetryPacket, AUTO)


PB_BIND(messaging_CommandPacket, messaging_CommandPacket, AUTO)


PB_BIND(messaging_AckPacket, messaging_AckPacket, AUTO)


PB_BIND(messaging_GPSData, messaging_GPSData, AUTO)







